apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-order-process-be-deployment
  labels:
    event: mi-order-process-be
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      event: mi-order-process-be
  template:
    metadata:
      labels:
        event: mi-order-process-be
    spec:
      containers:
      -
        image: wso2/mi-order-process-be
        name: mi-order-process-be
        imagePullPolicy: IfNotPresent
        ports:
        -
          name: web
          containerPort: 8290 
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    event: mi-order-process-be
spec:
  ports:
    -
      name: web
      port: 8290
      targetPort: 8290 
  selector:
    event: mi-order-process-be

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-getting-started-deployment
  labels:
    event: mi-getting-started
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      event: mi-getting-started
  template:
    metadata:
      labels:
        event: mi-getting-started
    spec:
      containers:
      -
        image: wso2/mi-getting-started:latest
        name: mi-getting-started
        imagePullPolicy: IfNotPresent
        ports:
        -
          name: web
          containerPort: 8290 
---
apiVersion: v1
kind: Service
metadata:
  name: mi-getting-started-service
  labels:
    event: mi-getting-started-be
spec:
  type: NodePort
  ports:
    -
      name: web
      port: 8290
      targetPort: 8290 
      nodePort: 32100
  selector:
    event: mi-getting-started
