blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://stackoverflow.com/questions/tagged/wso2-micro-integrator
    about: "If you have a question then please ask on Stack Overflow using the #wso2-micro-integrator tag."
  - name: Chat on help-micro-integrator Discord Channel
    url: https://discord.com/invite/Xa5VubmThw
    about: "Chat about anything else with the community."
