[server]
hostname = "localhost"
hot_deployment = false
# offset  = 10

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

## Following are set of example configs. Please refer docs for complete set of configurations.

# [transport.http]
# socket_timeout = 180000   # timeout in milliseconds
# disable_connection_keepalive = false
# connection_timeout = 90000 # in milliseconds

# [transport.jms]
# sender_enable = true
# listener_enable = true

# [[transport.jms.sender]]
# name = "myQueueSender"
# parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
# parameter.provider_url = "tcp://localhost:61616"
# parameter.connection_factory_name = "QueueConnectionFactory"
# parameter.connection_factory_type = "queue"
# parameter.cache_level = "producer"


#[[transport.jms.listener]]
# name = "myQueueConnectionFactory"
# parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
# parameter.provider_url = "tcp://localhost:61616"
# parameter.connection_factory_name = "QueueConnectionFactory"
# parameter.connection_factory_type = "queue"

# [transport.jndi.connection_factories]
# 'connectionfactory.QueueConnectionFactory' = "amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'"
# 'connectionfactory.TopicConnectionFactory' = "amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'"

# [transport.jndi.queue]
# jndiNameOfQueue = "physicalNameOfQueue"

# [transport.jndi.topic]
# jndiNameOfTopic = "physicalNameOfTopic"

# [transport.rabbitmq]
# sender_enable = true
# listener_enable = true

# [[transport.rabbitmq.sender]]
# name = "AMQPConnectionFactory"
# parameter.hostname = "localhost"
# parameter.port = 5672
# parameter.username = "guest"
# parameter.password = "guest"

# [[transport.rabbitmq.listener]]
# name = "AMQPConnectionFactory"
# parameter.hostname = "localhost"
# parameter.port = 5672
# parameter.username = "guest"
# parameter.password = "guest"

# [system.parameter]
# 'key' = "value"

# [[datasource]]
# id = "WSO2CarbonDB"  # "WSO2_COORDINATION_DB"
# url = "jdbc:mysql://localhost:3306/integratordb"
# username = "root"
# password = "root"
# driver = "com.mysql.jdbc.Driver"

# [management_api]
# protocols = "http"

# [[internal_apis.users]]
# user.name = "user-1"
# user.password = "pwd-1"

# [transaction_counter]
# enable = true
# data_source = "WSO2CarbonDB"
# update_interval = 2

# [mediation]
# synapse.global_timeout_interval = "120000"  # interval in milliseconds

# [secrets]
# secret_key = "[secret value]"

# [[service_catalog]]
# apim_host = "https://localhost:9443"
# enable = true
# username = "admin"
# password = "admin"

# [dashboard_config]
# dashboard_url = "https://localhost:9743/dashboard/api/"
