openapi: 3.0.1
info:
  title: PhoneVerifyAPI
  description: API Definition of PhoneVerifyAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/phones
paths:
  /validate/{phoneNumber}:
    get:
      parameters:
      - name: phoneNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
