name: Integration tests (Ubuntu, OpenJDK21)

on:
  push:
    branches:
      - '*'  # Runs on push to any branch
  pull_request:
    branches:
      - '*'  # Runs on any pull request
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: 1
            profile: tests-mediators_tests-other_tests-sample
          - id: 2
            profile: tests-service_tests-patches_service-samples
          - id: 3
            profile: tests-transport_tests-platform
          - id: 4
            profile: management-api_dss-tests
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21.0.4'
      - name: check mvn version
        run: echo "MAVEN_VERSION=$(mvn -v)"
      - name: check java version
        run: echo "JAVA_VERSION=$(java -version)"
      - name: Build in jdk21
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21.0.4'
      - name: check mvn version
        run: echo "MAVEN_VERSION=$(mvn -v)"
      - name: check java version
        run: echo "JAVA_VERSION=$(java -version)"
      - name: Print segment
        run: echo "Running build for segment ${{ matrix.profile }}"
      - name: JDK 21 Tests
        run: mvn -B clean install --file integration/pom.xml -P ${{ matrix.profile }} -fae
