name: Windows Build ( openjdk8 )

on: [push, pull_request]

jobs:
  windows:

    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v1
        with:
          java-version: openjdk8
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -fae -DskipTests
